channels = {
    "UCAjmpP7UAxdDGqXeg3bQqXg": "KML Tournaments",
    "UCM_WHDsygrK0MuLJCKIZ_Ng": "TEMPEST Vods",
    "UCXzmFLZfYaRfMokxpAORdnw": "Clemson Smash Club",
    "UC4USoymfPTvU_l4dcU-JB4Q": "Smash Bros Spain",
    "UC_zvHrklejXZRLZAd-8sFkA": "Hit'bAUX - SSB Auxerre",
    "UCtkWBSJDL-KiXGt27LxHWwA": "Cross Slash Studios",
    "UCnRfHYcd1XHv_NNy4RGhAfg": "SmashNorge",
    "UCkoN1Tageo4IF55KeSgCoVQ": "East Side Games CT",
    "UC_WdlA1raZNaG_wc0KvqAgA": "Xentric Gaming",
    "UCaoUdAowPfJd1ZqFMpyxFHQ": "SmashLibrary",
    "UCkegQrzOV-ADbj34249rLUw": "TFSmash",
    "UCUVBr3A3zpFmni5CsWNG9MA": "Rose City Smash Ultimate",
    "UCGhb1kdj5B2bPzGe70JhEHQ": "Smash Lorraine",
    "UCN2LK6PtMcOR7FPjeSf2TDg": "Post University Esports",
    "UCE0svsqYxtX25MkUwz5OXLg": "CStat Smash",
    "UCH3rxWzVrL4oq7-ShYx7Txw": "Super Smash Bros University",
    "UCq5K9oBD4C3TUWNegnvvrcw": "FSC Smash",
    "UC-DgOAMR_o3Oi9ijt44--wQ": "SmashLibrarian",
    "UCpdZK12UUSjuaCvI-W7xXqw": "UMBC Smash",
    "UCn_LdOLhjFF3_fgBrk-7y9A": "Collision Gaming Series",
    "UCi-07icquQIqVErKoysMVeg": "ClubSmashTV",
    "UCeZr_i9kW4CKkp7hQ52LnFQ": "Ultimate NU",
    "UC5AqnQ4vILvHW-qIL8xwFkw": "The Academy",
    "UCj5Bpq8HNS3iHLzwI4TH5lQ": "UGS Gaming",
    "UCYz-F3i4bsNCTiAzDGAPvpA": "EXE Events & Ecommerce",
    "UCj1J3QuIftjOq9iv_rr7Egw": "VGBootCamp",
    "UCFPaBLxpWvL-1ddHnWEjVdw": "スマブラオフ大会配信チャンネル",
    "UC5Z8xl051oZ_RN8l6D2koHg": "BuddBuds Tournaments",
    "UCKy0K5USA86vYuSu3C3Olnw": "Ikari VODs",
    "UCcJbXX0PzElQB0rDukL4IpQ": "University Of Akron Smash Bros",
    "UCxlRpd3600KIVyNaXMgPWAQ": "Snake VOD Archives",
    "UCizVTqahI6SldvdSAL_zIrA": "SmashFactorGaming",
    "UCKWgJxEhTv8ZOGrCP6rlrWA": "CJ Frozen",
    "UCKJi-4lbB3EwpLpC82OWFjA": "Beyond the Summit - Smash",
    "UC_62yzDG1VUUbjjnUmP4X_w": "渋谷BeeSmash",
    "UCIcsBVzRT-Hvz6bdM13rvfQ": "きょへ。",
    "UC1wbp2hvbSfnhiY14fTd9fg": "まえだくん",
    "UCJoMRVJFzKwnvPO-xY5V29w": "ケイロンチーノ",
    "UCov9k-GvJe6siwyrpJtj3Og": "ESAM",
    "UCvBHFNnPXt_re1WSdsennJg": "Hungrybox",
    "UCaMi7wgKkVMFdyEWBNoegEg": "九龍-KOWLOON-",
    "UCFjtfqgEgPCjGgTeTLemfdg": "Tornei Smash Bros Italia",
    "UCx_6Eq5ryrHtc8xIVz-p07w": "G3rd",
    "UCAFd6DMxEHgos24D1n3kt9g": "LonLonLeche",
    "UCkARopXyHR1K3_oHWkY-z2Q": "キョン",
    "UCG-pxOMgCQ3AtsxVPWk3XuQ": "Galint Gaming VODs",
    "UCvcLcxEPvxqhyryQM9eGsZg": "Unrivaled Tournaments",
    "UCZETiGSqhtpksswJBsZ_CbA": "Pyro's Smash VODs",
    "UC8m3PAhWQPKRk68oxBjv9_Q": "OrlandoGG",
    "UC4jxmGupCvjSZY2-sVfOepA": "Team FGSC",
    "UCI13aTPz_ip8lXGpjkGBCow": "Tamisuma.jp",
    "UCT9-m1Xp045f0SVQTt3wwSA": "CollisionSeries Clips",
    "UCxk9emHP8v92IkDxU54XWfg": "Mr Doughster",
    "UCHUlqk_Ymbz0nAgCx2qrlYg": "12G Smash",
    "UCZeKG9SOzzM35_lFdW7NGhg": "Smash Dimensions",
    "UCV7o-PWMq7P0h7RaD2K45Iw": "Mystic Squad TV",
    "UCalK9bzoFvkS4K83buMGgPQ": "HungryboxUltimate",
    "UCOp75dp_EYkgcvRA8AsQrbA": "CWU Esports ",
    "UCqB7d-vcBxxlccHB3oMk6ew": "Satellite Smash",
    "UCwQsmeDYGptH4-yW-yoTWwg": "Locus Crew",
    "UC7DfiIqFb_qB_MVSeoqboGQ": "Windu's Smash VODs",
    "UCbb0U-c5R6DoUpdgjgBwuRQ": "Sentry Esports",
    "UClMEettBM70dqmyy1UdYrIQ": "ICCS Smash",
    "UCDmA5DMLfDdmE2IFOxCUFYg": "The ABB Rchive",
    "UCD3H13Dg4xGprF2KYM3Q7bQ": "Ridgecrest Smash",
    "UCiII_LOKdQ-u8M_dxkonQIA": "Saskatchewan Smash",
    "UCxH_qUaJLvYKcSYoHpIhKpg": "HumanDotReplay",
    "UCb5H3-n9s7mqsX0Fr7ADKLg": "East Geek Smash",
    "UCIPILZtJTRTaAbqyPVJqiGw": "Seo Smash",
    "UCmr8D2Hb2V5qRIAUHCpQZkg": "RAT GLOBAL",
    "UCEcmRYwzcpxyHMBlRh-72cQ": "ありとる日記【スマブラSP】毎日更新中",
    "UCR-5GzBzIozuxnSGq6Enpnw": "ACT Smash",
    "UCdXfHKiElQ_xlgOixa_AUIw": "Vegas Smash Ultimate",
    "UC-KaYdfornbTu4lL58-RjpQ": "Chaparrito",
    "UCE2NI1BEQ_vFgGtfaw1TdYA": "Sylphe Gaming",
    "UC_u9_sjl2Q82zTK7WZwVr2A": "Toxic Tournaments",
    "UCb24KygL1W8NnXgA338zmfA": "SA Smash TV",
    "UC6MDOr9ORDlfsYH33U-RhmA": "北陸トライスマッシュ",
    "UC3YK9L8OcKDacwROp-mBXIw": "IHSEA Smash Vods",
    "UCexUF7a6Hh8xZ5XGLSKcsJw": "StreetDzine",
    "UCwuBPxeYpt0qMYjZ46vtEkQ": "Tournameta VODs",
    "UC4kjACt14ZasaxcUon0Fnhw": "BullCity Streams",
    "UCHnmD9__20XcSb8alr-UPHA": "スマわんこ",
    "UCt0kuaKzKcuWH8AnMzkvRFg": "Lausanne-Sport Esports",
    "UCDuSajivfJkqQVnCY8ryliw": "るりスマ",
    "UClXXNTpuFOKca25SL9bX6MA": "Smash SV",
    "UCLcKYt1UL7HTCBXk8oH_pKw": "Bureau Des Events",
    "UC5QJz8tgMXYDrilKKljviIw": "Channelスマブラ新都心",
    "UC4Kc1UlDqtjgNWr2nwK6Jfw": "Claim To Fame Entertainment",
    "UClALrxabMzc6kPsmWQFEjtw": "Pryme Crew",
    "UCxxgHAGuKpEC5ysUqEAhnag": "のほほンち",
    "UCVctcj20EkPSWKwZ3vuVRJw": "NIU Huskie Gaming",
    "UCjj5YveaLHrx4_DPOIzK1pA": "Arab Smash League",
    "UC9Ik6lHaV123-D_8yOSxX5A": "JadeYoRHa",
    "UC_NTsQKtPmygB8d_BbkUhkA": "Namis eSports",
    "UC4fs7e4zjlppBnaCe6OyRHA": "SmashGt Live",
    "UCoGbeeXeKenX7yXsF09qckA": "しのスマ",
    "UCtZsOgPnj_rsT_Zoa_d7Tuw": "L4st",
    "UC_eSRZy9Y9lsgso7mF4Q4nA": "Temporada de Patos",
    "UCHNfTCiizaDJ8CL3Lh9fmWw": "kept Rush Gaming",
    "UC9RCcF8FGZeOjFTdIx2z8qQ": "キシル/Kishiru",
    "UCaW3vd50l8QDJ5EjJfR0P-g": "VGBC 日本",
    "UCVfu96BLrC7aUabLbYM-lGQ": "JMLeague",
    "UC2B0Io6bB6Oxn_e9Ww6IPfg": "VegacyTV",
    "UCNIInaN2HfHwnlileVI_ZQQ": "Smash Association Loire Touraine",
    "UC_pylEiLYdF5hwDGW8XlH2Q": "CR_Jetstream",
    "UCT6JSLjnxo9KS1pMlE0_2Pw": "Fenryr",
    "UCt8xPNGuJ1N6n5xmprZceYw": "Kentoのゲームちゃんねる。",
    "UC8QVPYl_yHc7ixElDWWkp3g": "UNSW Smash",
    "UCydYXSGB15d9fwU9nld-NEQ": "GenGAME",
    "UCcZK6jj28_nvDW-SSzwMa-Q": "SilentiumSSB",
    "UCOjSdh6EUd_JhwWxOFSDAKQ": "Wumbo Official",
    "UCIUprX7V-HipNv7byQksZlQ": "AnG esports",
    "UCFLZu-OMg_iFoeXbufFNoAw": "Hashtag Arena",
    "UC_e1uK9t_KYntXoi54oU47w": "闘龍門スマブラ",
    "UCn2OOWys3-vEver0cHf7lYw": "Just Tryna Smash",
    "UClIuCiBN-UIsTZb0WlhRo0Q": "2GGaming",
    "UClH8scJNKPNFRsMyRHWEIWg": "CleanKill Esports",
    "UCfoTAd662mucYxhZo7YHR9A": "Zackray / ザクレイ",
    "UCyHm_6RX9H4Dn1oxHVwSbPg": "Source Gaming Lounge",
    "UC-oVHcDinUFakWbqUGsqO-g": "SmashlogTV - SSBU",
    "UCp9xvs8Nsh-XRDia35ATfGA": "SweetSpotCR",
    "UCuBhMqosgW-ECZjJZ9pv0Dg": "Tourney Locator",
}
